name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GO_VERSION: "1.23.4"
  NODE_VERSION: "20.10.0"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          go-version: ${{ env.GO_VERSION }}
      - name: Install Node dependencies
        run: cd debugger && npm install
      - name: Run Node build
        run: cd debugger && npm run build
      - uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}